# Generated by Django 4.0.3 on 2023-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='sold',
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
